apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job-15-mins
spec:
  schedule: "0,15,30,45 * * * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          containers:
          - name: main
            image: luksa/batch-job
          restartPolicy: OnFailure
