apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          readinessProbe:
            exec:
              command:
                - "ls"
                - "/var/ready"
          ports:
            - name: http
              containerPort: 8080
