apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    name: kubia-manual
    creation_method: manual
    env: prod
spec:
  containers:
  - name: kubia
    image: beastz/kubia
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
