apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
  labels:
    name: kubia-liveness
spec:
  containers:
  - name: kubia
    image: beastz/kubia-unhealthy
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
